<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lease Agreement - {{ $lease->property->code }}</title>
    <style>
        body {
            font-family: 'Times New Roman', serif;
            line-height: 1.6;
            color: #333;
            margin: 40px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            margin-bottom: 30px;
            padding-bottom: 10px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            font-weight: bold;
            text-transform: uppercase;
            text-decoration: underline;
            margin-bottom: 10px;
        }
        .grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .grid-row {
            display: table-row;
        }
        .grid-cell {
            display: table-cell;
            padding: 5px;
            border-bottom: 1px solid #eee;
        }
        .label {
            font-weight: bold;
            width: 30%;
        }
        .signatures {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }
        .signature-box {
            width: 45%;
            border-top: 1px solid #333;
            padding-top: 10px;
            text-align: center;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 0.8em;
            color: #777;
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>RESIDENTIAL LEASE AGREEMENT</h1>
        <p>Property Code: {{ $lease->property->code }}</p>
    </div>

    <div class="section">
        <p>This Residential Lease Agreement ("Agreement") is made and entered into on {{ $lease->created_at->format('F j, Y') }}, by and between:</p>
        
        <div class="grid">
            <div class="grid-row">
                <div class="grid-cell label">LANDLORD:</div>
                <div class="grid-cell">{{ $lease->landlord->name }}</div>
            </div>
            <div class="grid-row">
                <div class="grid-cell label">TENANT:</div>
                <div class="grid-cell">{{ $lease->tenant->name }}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">1. PROPERTY</div>
        <p>The Landlord agrees to rent to the Tenant the following property located at:</p>
        <p><strong>{{ $lease->property->title }}</strong><br>
        {{ $lease->property->location }}, {{ $lease->property->town }}, {{ $lease->property->province }}</p>
    </div>

    <div class="section">
        <div class="section-title">2. TERM</div>
        <p>The term of this lease shall begin on <strong>{{ $lease->start_date->format('F j, Y') }}</strong> and end on <strong>{{ $lease->end_date->format('F j, Y') }}</strong>.</p>
    </div>

    <div class="section">
        <div class="section-title">3. RENT</div>
        <p>The Tenant agrees to pay the Landlord a monthly rent of <strong>K{{ number_format($lease->monthly_rent, 2) }}</strong>.</p>
    </div>

    <div class="section">
        <div class="section-title">4. SPECIFIC TERMS & CONDITIONS</div>
        <div style="white-space: pre-wrap; background: #f9f9f9; padding: 15px; border-radius: 5px; border: 1px solid #ddd;">{{ $lease->content }}</div>
    </div>

    <div class="section">
        <div class="section-title">5. SIGNATURES</div>
        <p>By signing below, the parties acknowledge that they have read and understood the terms of this agreement.</p>
        
        <div class="signatures">
            <div class="signature-box">
                <p>Landlord Signature</p>
                <p>{{ $lease->landlord->name }}</p>
                @if($lease->landlord_signed_at)
                    <p><small>Signed electronically on: {{ $lease->landlord_signed_at->format('Y-m-d H:i') }}</small></p>
                @endif
            </div>
            <div class="signature-box" style="float: right;">
                <p>Tenant Signature</p>
                <p>{{ $lease->tenant->name }}</p>
                @if($lease->tenant_signed_at)
                    <p><small>Signed electronically on: {{ $lease->tenant_signed_at->format('Y-m-d H:i') }}</small></p>
                @endif
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>

    <div class="footer">
        <p>Generated by Maambo Rental Platform - System ID: {{ $lease->id }}</p>
        <p>This document is a legally binding agreement.</p>
    </div>

    <div class="no-print" style="position: fixed; top: 20px; right: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #e11d48; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold;">
            Print Agreement
        </button>
    </div>
</body>
</html>
